version: '3.4'
services:
  sut:
    build:
      context: .
      target: development
    command: bash -c "bin/setup && bin/rails test && bundle exec brakeman"
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:10
  redis:
    image: redis:3.2
