version: '3.0'

services:
  web:
    build: .
    command: bin/rails server -b 0.0.0.0
    volumes:
      - campo-sync:/app:nocopy
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
  worker:
    build: .
    command: bundle exec sidekiq
    volumes:
      - campo-sync:/app:nocopy
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:10
  redis:
    image: redis:3.2

volumes:
  campo-sync:
    external: true
