version: '3.4'

services:
  sut:
    build:
      context: .
      target: base
    command: bash -c "bin/setup && bin/rails test && bundle exec brakeman"
    volumes:
      - .:/campo
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:10
  redis:
    image: redis:3.2
