version: '3.0'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:10
  redis:
    image: redis:3.2
