version: '3.0'
services:
  web:
    build: .
    command: bin/rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
  worker:
    build: .
    command: sidekiq
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:10
  redis:
    image: redis:3.2
