version: '3.4'

services:
  web:
    build:
      context: .
      target: base
    volumes:
      - .:/campo
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:10
  redis:
    image: redis:3.2
